[package]
edition = "2021"
name = "image-png-demo"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.6"
rgb = "0.8.33"
imagequant = "4.0"